apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
commonlabels:
  app.kubernetes.io/name: traefik
resources:
- clusterrole.k8s.yaml
- clusterrolebinding.k8s.yaml
- crds.yaml
- deployment.k8s.yaml
- namespace.k8s.yaml
- service.k8s.yaml
- serviceaccount.k8s.yaml
